site_name: PhasicTonic

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    features:
      - navigation.tabs

plugins:
    - search                           # make sure the search plugin is enabled
    - mkdocstrings:                    # plugin for generating documentation from Python docstrings
        handlers:                      # handler is responsible for loading and parsing source files
          python:                      # set handler is for Python
            path: [src]                      
            options:                   # configuration of options for the Python handler
              docstring_style: numpy   # style of docstrings (convention followed)
              show_source: true        # include a link to the source code
              show_members: source     # configures the order in which members (methods, attributes, etc.) are displayed.
                                       # If set to 'source', it means the order in the source code will be maintained.
    - gen-files:
        scripts:
            - docs/gen_ref_pages.py     # script for generating reference pages
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation
    - section-index                    # plugin for creating section index
    - gallery:
        examples_dirs: docs/examples          # path to your example scripts
        gallery_dirs: docs/generated/gallery  # where to save generated gallery
nav:
    - Home: index.md
    - Install: install.md
    - Tutorials: generated/gallery
    - API: reference/
    - About: about.md
